apiVersion: v1
kind: Service
metadata:
  name: django-blog-service
  namespace: app
spec:
  # MetalLB를 통해 외부 IP를 받도록 LoadBalancer로 노출
  type: LoadBalancer
  selector:
    app: django-blog-app
  ports:
  - port: 8000
    targetPort: 8000
